spring:
  datasource:
    username: 
    url: 
    driverClassName: org.mariadb.jdbc.Driver
    password: 
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: 
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  redis:
    host: i9d208.p.ssafy.io
    port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 9091
  servlet:
    jsp:
      init-parameters:
        development: true
springdoc:
  swagger-ui:
    path: /api/api.html

management:
  endpoints:
    web:
      exposure:
        include: health
cloud:
  aws:
    s3:
      bucket: 
    stack.auto: false
    region.static:
    credentials:
      accessKey: 
      secretKey:
    ses:
      access-key: 
      secret-key: 

#OpenVidu
OPENVIDU_URL: 
OPENVIDU_SECRET: 

#Cloudfront
CLOUD_FRONT_URL: 

#aws
AWS_ACCESS_KEY: 
AWS_SECRET_KEY: 

#img
DEFAULT_IMG: logo.png

#naver
NAVER_CLIENT_ID : 
NAVER_SECRET_KEY : 

#domain
FRONT_URL :
